const listaDePresentes = [
  "Jogo de Panelas Antiaderente",
  "Liquidificador",
  "Batedeira",
  "Fritadeira",
  "Jogo de Taças de Cristal",
  "Aspirador de Pó Vertical",
  "Jogo de Cama Casal",
  "Kit de Toalhas de Banho",
  "Cafeteira Expresso",
  "Jogo de Talheres 24 Peças",
  "Panela de Pressão",
  "Jogo de Potes Herméticos",
  "Chaleira Elétrica",
  "Assadeira Retangular",
  "Jogo de Copos de Vidro",
  "Porta Temperos",
  "Ralador Multifuncional",
  "Forma de Bolo Redonda",
  "Espátulas de Silicone",
  "Escorredor de Macarrão",
  "Pegador de Salada",
  "Tábua de Corte",
  "Descascador de Legumes",
  "Moinho de Pimenta e Sal",
  "Panelas",
  "Coador de Café",
  "Jogo de Canecas",
  "Forma de Pizza",
  "Conjunto de Assadeiras Antiaderentes",
  "Pote de Vidro com Tampa",
  "Balança Digital de Cozinha",
  "Faqueiro de Sobremesa",
  "Jogo de Bowls",
  "Pipoqueira Elétrica",
  "Suporte para Panela",
  "Kit de Medidores",
  "Pegador de Massa",
  "Jogo de Travessas",
  "Kit de Utensílios de Silicone",
  "Conjunto de Garrafas para Óleo e Vinagre",
  "Panela de Aço Inox",
  "Kit de Panelas Pequenas",
  "Conjunto de Sobremesa",
  "Panela Elétrica Multiuso",
  "Forma de Pudim",
  "Jogo de Pratos Rasos e Fundos",
  "Conjunto de Canecas Divertidas",
  "Porta Talheres de Madeira",
  "Kit de Formas para Pão",
  "Conjunto de Bowls de Vidro",
  "Jogo de Panelas Antiaderente",
  "Pratos de Sobremesa",
  "Jogo de Copos para Vinho",
  "Porta Condimentos Giratório",
  "Kit de Utensílios de Madeira",
  "Conjunto de Assadeiras Redondas",
  "Kit de Utensílios para Churrasco",
  "Espremedor Manual de Frutas",
  "Jogo de Travessas de Vidro Temperado",
  "Forma de Gelo Criativa",
  "Conjunto de Colheres Medidoras",

];

module.exports = { listaDePresentes };
